release: arkanoid.ASM KEYB.OBJ
	ML /W3 /WX KEYB.OBJ arkanoid.ASM /Fe arkanoid.EXE

debug: arkanoid.ASM KEYBD.OBJ
	ML /Zi /W3 /WX KEYBD.OBJ arkanoid.ASM /Fe arkanoidD.EXE
	
KEYB.OBJ: KEYB.ASM
	ML /c /W3 /WX /FoKEYB.OBJ /Ta KEYB.ASM
	
KEYBD.OBJ: KEYB.ASM
	ML /c /Zi /W3 /WX /FoKEYBD.OBJ /Ta KEYB.ASM

clean:
	del *.EXE
	del *.OBJ

cv: debug
	cv /s /43 arkanoidD.EXE
